// src/components/editor.tsx
import { useRef, useEffect } from 'react';
import * as monaco from 'monaco-editor/esm/vs/editor/editor.api';

export const AppEditor = () => {
  const containerRef = useRef<HTMLDivElement | null>(null);
  const editorRef = useRef<monaco.editor.IStandaloneCodeEditor | null>(null);

  const getDefaultCode = (): string => {
    return [
      '; *****************************************************',
      ';  Welcome to Relay Computer Assembly (RCASM)',
      ';',
      ';  Start typing your program below or open an example',
      ';  from the examples folder top left',
      '; *****************************************************',
      '',
      '',
    ].join('\n');
  };

  let changeTimeoutId: number | undefined;
  const onCodeChange = () => {
    // Debounce change by up to 500ms
    clearTimeout(changeTimeoutId);
    changeTimeoutId = setTimeout(() => {
      const code = editorRef.current?.getValue();
      if (code) {
        localStorage.setItem('code', code);
      }
    }, 500);
  };

  useEffect(() => {
    if (!containerRef.current) return;

    if (!editorRef.current) {
      const code = localStorage.getItem('code') || getDefaultCode();

      editorRef.current = monaco.editor.create(containerRef.current, {
        theme: window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches ? 'vs-dark' : 'vs-light',
        value: code,
        language: 'rcasm',
        lineNumbers: 'on',
        renderLineHighlight: 'none',
        padding: { top: 15 },
        automaticLayout: true,
        scrollBeyondLastLine: true,
      });

      editorRef.current.onDidChangeModelContent(() => onCodeChange());
    }

    return () => {
      editorRef.current?.dispose();
      editorRef.current = null;
    };
  }, []);

  return <div style={{ height: '100%' }} ref={containerRef}></div>;
};

// src/app/editor/editor.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-ride-editor',
  templateUrl: './editor.component.html'
})
export class EditorComponent {
  @Output() codeChanged = new EventEmitter<string>();

  stateType: string = 'info';
  stateText: string = 'ready';

  editor: monaco.editor.ICodeEditor | null = null;

  constructor(private http: HttpClient) { }

  editorOptions = <monaco.editor.IStandaloneEditorConstructionOptions>{
    language: 'rcasm',
    lineNumbers: 'on',
    renderLineHighlight: 'none',
    scrollBeyondLastLine: true,
    theme: (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) ? 'vs-dark' : 'vs-light',
    padding: { top: 15 }
    // minimap: { enabled: false }
  };

  onInit(editor: monaco.editor.ICodeEditor) {
    this.editor = editor;

    editor.onDidChangeModelContent(() => {
      const code = editor.getModel()?.getValue()
      if (code) {
        localStorage.setItem("code", code);
        this.codeChanged.emit(code);
      }
    });

    editor.onDidChangeCursorPosition(e => {
      this.stateText = `Ln ${e.position.lineNumber}, Col ${e.position.column}`;
    });

    const code = localStorage.getItem("code") || this.getDefaultCode();
    editor.getModel()?.setValue(code);
  }

  getDefaultCode(): string {
    return [
      ';*****************************************************',
      '; Welcome to Relay Computer Assembly (RCASM)',
      ';',
      '; Start typing your program below or open an example',
      '; using the import menu at the top right',
      ';*****************************************************',
      '',
      ''].join('\n');
  }

  loadExample(example: string) {
    this.http.get(`/assets/examples/${example}`, { responseType: 'text' }).subscribe(data => {
      this.editor?.getModel()?.setValue(data);
    });
  }

}

<ngx-monaco-editor style="height: 100%" [options]="editorOptions" (init)="onInit($event)" class="editor"></ngx-monaco-editor>
<div class="editor-footer" cds-layout="horizontal gap:xs align:vertical-center">
  <span cds-text="secondary regular" [innerHTML]="stateText"></span>
</div>
