// src/app/output/output.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-ride-output',
  templateUrl: './output.component.html'
})
export class OutputComponent {

  stateType: string = 'info';
  stateText: string = 'ready';

  @Input()
  set dasm(val: string) {
    this.editor?.getModel()?.setValue(val);
  }

  editor: monaco.editor.ICodeEditor | null = null;

  editorOptions = <monaco.editor.IStandaloneEditorConstructionOptions>{
    language: 'rcdsm',
    lineNumbers: 'off',
    renderLineHighlight: 'none',
    readOnly: true, domReadOnly: true,
    scrollBeyondLastLine: true,
    theme: (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) ? 'vs-dark' : 'vs-light',
    padding: { top: 15 },
    minimap: { enabled: false }
  };

  onInit(editor: monaco.editor.ICodeEditor) {
    this.editor = editor;
  }

  setStateAssembledOk() {
    this.stateType = 'success';
    this.stateText = 'Assembled OK';
  }
  setStateAssembledWithWarnings(warnCount: number) {
    this.stateType = 'warning';
    this.stateText = `Assembled with ${warnCount} warning${warnCount === 1 ? '' : 's'}`;
  }
  setStateAssembledWithErrors(errorCount: number, warnCount: number) {
    const errorText = `${errorCount} error${errorCount === 1 ? '' : 's'}`;
    const warningText =  warnCount > 0 ? `, ${warnCount} warning${warnCount === 1 ? '' : 's'}` : '';
    this.stateText = `<b>Assembly failed:</b> ${errorText}${warningText}`;
    this.stateType = 'danger';
  }
}

  <ngx-monaco-editor style="height: 100%" [options]="editorOptions" (init)="onInit($event)" class="editor"></ngx-monaco-editor>
<clr-alert [clrAlertType]="stateType" [clrAlertAppLevel]="true" [clrAlertClosable]="false" class="editor-footer">
  <clr-alert-item>
    <span class="alert-text" [innerHTML]="stateText">
    </span>
  </clr-alert-item>
</clr-alert>

// src/components/output.tsx
import { useRef, useEffect } from 'react';
import * as monaco from 'monaco-editor/esm/vs/editor/editor.api';

export const AppOutput = () => {
  const containerRef = useRef<HTMLDivElement | null>(null);
  const editorRef = useRef<monaco.editor.IStandaloneCodeEditor | null>(null);

  useEffect(() => {
    if (!containerRef.current) return;

    if (!editorRef.current) {
      editorRef.current = monaco.editor.create(containerRef.current, {
        value: ['function x() {', '\tconsole.log("Hello world!");', '}'].join('\n'),
        theme:
          window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches
            ? 'vs-dark'
            : 'vs-light',
        language: 'rcdsm',
        lineNumbers: 'off',
        renderLineHighlight: 'none',
        readOnly: true,
        domReadOnly: true,
        padding: { top: 15 },
        minimap: { enabled: false },
        glyphMargin: false,
        automaticLayout: true,
        scrollBeyondLastLine: false
      });
    }

    return () => {
      editorRef.current?.dispose();
      editorRef.current = null;
    };
  }, []);

  return <div style={{ height: '100%' }} ref={containerRef}></div>;
};
